"
I am an example class
"
Class {
	#name : 'RowanSample9V3Class1',
	#superclass : 'Object',
	#instVars : [
		'ivar1'
	],
	#category : 'RowanSample9V3-Core'
}

{ #category : 'accessing' }
RowanSample9V3Class1 >> A_bc123 [ ^1
]

{ #category : 'accessing' }
RowanSample9V3Class1 >> Foo [ ^1
]

{ #category : 'accessing' }
RowanSample9V3Class1 >> _123Abc [ ^1
]

{ #category : 'accessing' }
RowanSample9V3Class1 >> _ABC123 [ ^1
]

{ #category : 'accessing' }
RowanSample9V3Class1 >> _abc123 [ ^1
]

{ #category : 'accessing' }
RowanSample9V3Class1 >> foo [ ^1
]
